source 'https://rubygems.org'

gem 'middleman', '~> 4.3.5'
gem 'middleman-blog'
gem 'middleman-livereload'
gem 'middleman-syntax'
gem 'middleman-minify-html'
gem 'middleman-ogp', github: 'unhappychoice/middleman-ogp'
gem 'nokogiri'
gem 'slim'
gem 'redcarpet', '~> 3.5'
gem 'builder', '~> 3.0'
gem 'mgd'
gem 'activesupport'
gem 'github_api'