source 'https://rubygems.org'

gem 'activesupport'
gem 'builder', '~> 3.2'
gem 'github_api'
gem 'inline_svg'
gem 'mgd'
gem 'middleman', '~> 4.5.0'
gem 'middleman-blog'
gem 'middleman-livereload'
gem 'middleman-syntax'
gem 'middleman-minify-html'
gem 'middleman-ogp'
gem 'nokogiri'
gem 'redcarpet', '~> 3.6'
gem 'slim'
